service: DTBZoluxiones
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        -  arn:aws:dynamodb:us-west-2:552820124213:table/planetas

functions:
           
  listarPlanetasSWAPI:
    handler: src/listarPlanetasSWAPI.listarPlanetasSWAPI
    events:
      - httpApi:
          path: /listarPlanetasSWAPI
          method: get

  listarPlanetasDynamoDB:
    handler: src/listarPlanetasDynamoDB.listarPlanetasDynamoDB
    events:
      - httpApi:
          path: /listarPlanetasDynamoDB
          method: get

  crearPlanetas:
    handler: src/crearPlanetas.crearPlanetas
    events:
      - httpApi:
          path: /crearPlaneta
          method: post
resources: 
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: planetas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH